### ISSUE TITLE
Incompatible with Allow Tool

### ISSUE THREAD

**Issue by paulo27ms** [Dubwise56/Dubs-Performance-Analyzer#1]
For some reason this mod removes the option to right-click the Allow Tool utilities. You can right-click them from the architect menu still but if you select an item in the world, you can no longer right-click for more options... only took 3 hours to figure out it was this mod among my other 170.

It'd also be useful if the options this mod provides were a bit more informative for the average user, "Fix Game" sounds nice but not that helpful in the grand scheme of things.

Either way, thanks for this mod, it's something that I'm sure will be useful to debug stuff in the future, just won't keep it installed all the time for now (but perhaps it wasn't designed to be anyway).

**Comment by Dubwise56** [comment]
im spamming updates to it while im testing with people on my discord to find what mods are murdering fps, options and fixes are constantly changing, the fix game option already changed, so don't try actually using it until its had a full release or unless you're on the discord to chat about it.

already talked about allow tool with a couple people, its probably the gizmo grid optimization so i removed the event filtering on it for the draw which might fix it, its already on the current master

**Comment by paulo27ms** [comment]
Ok! I'll keep an eye out and probably hop on the discord then.

**Comment by ZXQWAS** [comment]
Just a note that I confirm that this was fixed recently.
