### ISSUE TITLE
Just a general question.

### ISSUE THREAD

**Issue by bombcat2015** [Dubwise56/Dubs-Performance-Analyzer#6]
Just to start here, I think your mods are awesome...I use them as a benchmark for excellence in RimWorld modding and model some of my personal modding with your efficient coding style in mind.  Five stars etc etc.  Thanks for the work you do.

I noticed that your image here https://imgur.com/85FHPgS shows an interface that isn't currently available on the version (most current on steam)...and if it is available I'm unable to view it.  The arrows next to "UPDATE", "GUI", "TICK" and the Max, Average, Percent, Totals, Call, Name columns at the top of the GUI.  It could be I'm just brain damaged and missing something, but I've tried like hell to replicate and am unable to do so.  Could you make me feel less crazy and tell me that version (the one used on your "Slow Mods" google sheet) hasn't been released...or make me feel more stupid and explain how you enable that view.  

I would have asked in Steam forums but I've been using the DRM version since before RimWorld was released on Steam (Early Adopter).  I apologize if this is not the correct location for such a request.

Thanks in advance.

Bombcat

**Comment by Dubwise56** [comment]
that's wiri's branch which isn't stable yet, some people use it for certain tests on my discord but that's all for now, my master branch and the version on steam is stable

**Comment by bombcat2015** [comment]
Dubs, thanks for the quick response.  I may hop on your discord as I enjoy pushing Rimworld past it's limits then trying to make it run smoothly lol.  I found the fork you were referring to and am giving it a test spin.  Thanks again.
